import axios from 'axios';
import Head from 'next/head'
import { useEffect, useState } from 'react';
import BrowserScript from "../lib/core/views"
import styles from '../styles/Home.module.css'

let _bs = null;
const initialize = () => {
  const bs = new BrowserScript(window.document.getElementById('main-view'))
  const code = async function() {
    bs.text("## Calculate your taxes!");
    const country = bs.radio("Where do you live?", ["Canada", "United States"]);
    bs.text(`Your Country: **${country ? country : ""}**`);
    const value = bs.input(
      "Your annual income",
      {
        defaultValue: 0,
        placeholder: "Ex: 10000",
        type: "number",
      }
    );
    const taxRate = bs.slider(
      "Your Tax Rate",
      {
        defaultValue: 0,
        min: 0,
        max: 100,
        type: "number",
      });
    if (value && taxRate) {
      bs.text(`## Your tax is: $${value * taxRate / 100}!`);
    }
    const checked = bs.checkbox("I don't want to pay taxes")
    bs.text(`You are checked: **${checked}**`);
    const clicked = bs.button("Submit")
    bs.image("https://i.imgur.com/CAcnA3e.jpeg", {width: '100', height: '100'});
    bs.audio("http://ringelkater.de/Sounds/2geraeusche_tiere/dino_tyrannosaurus1.wav");
    const response = await axios.get("https://www.mockachino.com/e065c9e2-cd3f-4a/users");
    bs.text("Hello " + JSON.stringify(response.data));
    if (clicked) {
      const response = await axios.post("https://www.mockachino.com/e065c9e2-cd3f-4a/users");
      bs.text('Submitted! ' + JSON.stringify(response.data));
    }
  }
  bs.start(code);
  _bs = bs;
}
export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined" && _bs === null) {
      initialize();
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="main-view">
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
