import Head from 'next/head'
import { useEffect, useState } from 'react';
import BrowserScript from "../lib/core/views"
import styles from '../styles/Home.module.css'

let _bs = null;
const initialize = () => {
  const bs = new BrowserScript(window.document.getElementById('main-view'))
  const code = async function() {
    bs.text("## Hello world! This is a test of my software");
    const value = bs.input({defaultValue: 0, label: "Your annual income", placeholder: "Ex: 10000", type: "number"});
    if (value) {
      bs.text(`## Your tax is: $${value * 0.15}!`);
    }
    const clicked = bs.button({text: "Hello"})
    if (clicked) {
      bs.text('Submitting');
    }
  }
  bs.start(code);
  _bs = bs;
}
export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined" && _bs === null) {
      initialize();
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="main-view">
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
