import Head from 'next/head'
import { useEffect, useState } from 'react';
import BrowserScript from "../lib/core/views"
import styles from '../styles/Home.module.css'

let _bs = null;
const initialize = () => {
  const bs = new BrowserScript(window.document.getElementById('main-view'))
  const code = async function() {
    bs.text("## Hello world! This is a test of my software");
    const country = bs.radio("Where do you live?", ["Canada", "United States"]);
    bs.text(`Your Country: **${country ? country : ""}**`);
    console.log(country);
    const value = bs.input(
      "Your annual income",
      {
        defaultValue: 0,
        placeholder: "Ex: 10000",
        type: "number",
      }
    );
    const taxRate = bs.slider(
      "Your Tax Rate",
      {
        defaultValue: 0,
        min: 0,
        max: 100,
        placeholder: "Ex: 10000",
        type: "number",
      });
    if (value && taxRate) {
      bs.text(`## Your tax is: $${value * taxRate / 100}!`);
    }
    const clicked = bs.button("Submit")
    if (clicked) {
      bs.text('Submitting');
    }
  }
  bs.start(code);
  _bs = bs;
}
export default function Home() {
  useEffect(() => {
    if (typeof window !== "undefined" && _bs === null) {
      initialize();
    }
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="main-view">
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}
